### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

### ISSUE THREAD

**Issue by mtthwryn** [magic-research/bubogpt#11]
I am running this on a docker image, does anyone know a fix for this error?

**Comment by mtthwryn** [comment]
Found the solution, make the cuda devices = 0 before importing torch
```
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import torch
```

**Comment by Haoqiu-Yan** [comment]
Agree with it! Another solution is to add CUDA_VISIBLE_DEVICES=0 in the front of  torchrun cmd:
`CUDA_VISIBLE_DEVICES=0 torchrun `
