### ISSUE TITLE
No module named 'constants.constant'; 'constants' is not a package

### ISSUE THREAD

**Issue by R1gd** [magic-research/bubogpt#3]
Hi,

The install of requirements.txt went well, however i am getting the below error, after installing pip install constants the error is still there :

`C:\Users\User1\Downloads\bubogpt-main\bubogpt-main>python eval_scripts/qualitative_eval.py --cfg-path eval_configs/mmgpt4_eval.yaml --gpu-id 0
Traceback (most recent call last):
  File "C:\Users\User1\Downloads\bubogpt-main\bubogpt-main\eval_scripts\qualitative_eval.py", line 15, in <module>
    from constants.constant import LIGHTER_COLOR_MAP_HEX
ModuleNotFoundError: No module named 'constants.constant'; 'constants' is not a package`

**Comment by bingykang** [comment]
Hi @R1gd,

Thank you for trying with our code.

Can you try `export PYTHONPATH=/path/to/bubogpt` before running the above command?

**Comment by R1gd** [comment]
It seems to be solved after a fresh install, thank you :)
