### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement mmmengine==0.7.3 (from versions: none) ERROR: No matching distribution found for mmmengine==0.7.3

### ISSUE THREAD

**Issue by mtthwryn** [magic-research/bubogpt#4]
When running

pip3 install mmmengine==0.7.3 \
  mmcv==2.0.0 -f https://download.openmmlab.com/mmcv/dist/cu117/torch2.0/index.html \
  git+https://github.com/facebookresearch/segment-anything.git \
  git+https://github.com/IDEA-Research/GroundingDINO.git

**Comment by bingykang** [comment]
Sorry for the typo, it should be 

```bash
pip3 install mmengine==0.7.3
```

The readme has been updated.
